name: AgeTaxoDeepL
channels:
  - pytorch
  - nvidia # Good channel for CUDA-related packages
  - defaults
dependencies:
  # == Core Packages ==
  - python=3.12.9
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pandas=2.2.3
  - numpy=2.0.1
  - pillow=11.1.0


